# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Jiyoung Jang
description: >- # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of the site
url: "https://jiyoungj.github.io" # the base hostname & protocol for the site
og_image: /assets/img/preview.png
google_analytics: "UA-174916760-1"

header:
  pages:
    - name: Home
      slug: /
    - name: Research
    - name: Contact

footer:
  show_powered_by: true
#  “CONTACT” and “FOLLOW”: go to /_includes/footer.html and remove <!-- xxx --!>
#  contact: 
#    - name: Email
#      link: mailto:jiyoung@ucsb.edu
# follow:
#    - name: GitHub
#      link: http://github.com/YourUsername

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
